spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcurso?useSSL=false
    username: root
    password: vw2m6w2m7
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect